server:
  port: 6098

spring:
  datasource:
    password: Meshree
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  config:
    activate:
      on-profile:
      - dev

---


server:
  port: 6098
spring:
  datasource:
    password:
    url: jdbc:h2:file:C:/h2data/sample
    username: sa
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  config:
    activate:
      on-profile:
      - test